name: AI News Bot (Python)

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC
  workflow_dispatch:
    inputs:
      keyword:
        description: 'News search keyword'
        required: false
        default: 'artificial intelligence'
      style:
        description: 'Writing style'
        required: false
        default: 'professional'
        type: choice
        options:
          - professional
          - casual
          - academic
      max_articles:
        description: 'Maximum articles to generate'
        required: false
        default: '3'
        type: choice
        options:
          - '1'
          - '2'  
          - '3'
          - '5'

permissions:
  contents: read
  issues: write

jobs:
  generate-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run AI News Bot
      env:
        EVENTREGISTRY_API_KEY: ${{ secrets.EVENTREGISTRY_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        INPUT_KEYWORD: ${{ inputs.keyword || 'artificial intelligence' }}
        INPUT_STYLE: ${{ inputs.style || 'professional' }}
        MAX_ARTICLES: ${{ inputs.max_articles || '3' }}
      run: |
        python src/news_bot.py \
          --keyword "$INPUT_KEYWORD" \
          --style "$INPUT_STYLE" \
          --max-articles "$MAX_ARTICLES"
      
    - name: Upload generated articles
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ai-news-articles-${{ github.run_number }}
        path: "*.md"
        retention-days: 30