name: Debug Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Debug secret availability
      env:
        EVENTREGISTRY_API_KEY: ${{ secrets.EVENTREGISTRY_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo "🔍 Debugging secret availability..."
        
        if [ -n "$EVENTREGISTRY_API_KEY" ]; then
          echo "✅ EVENTREGISTRY_API_KEY is available (${#EVENTREGISTRY_API_KEY} chars)"
        else
          echo "❌ EVENTREGISTRY_API_KEY is NOT available"
        fi
        
        if [ -n "$GOOGLE_API_KEY" ]; then
          echo "✅ GOOGLE_API_KEY is available (${#GOOGLE_API_KEY} chars)"  
        else
          echo "❌ GOOGLE_API_KEY is NOT available"
        fi
        
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        
    - name: List available environment variables
      run: |
        echo "🔧 Available environment variables:"
        env | grep -E "(API|KEY)" || echo "No API/KEY variables found"